docs/05-supporting-quotes.md, docs/examples/ember-engine-circle-config.yml, docs/examples/stickybits-circle-config.yml
- Provides a folder and initial examples
- The talk needs examples!
----
=> [update] adds example .circleci/config.yml(s)

.circleci/config.yml, .spelling
- Fixes Circle Config
- Adds workflow
----
=> [bug] adds workflow to .circleci/config.yml

.spelling, docs/01-talk-objectives.md, docs/03-key-points.md, docs/11-implementing-ci.md
- Various bug fixes + links
----
=> [bug] adds various spelling tweaks + links

.circleci/config.yml
=> [bug] attempt to fix circleci config

docs/04-ci-solves-problems.md
- Copy updates to the Solves Problem readme
=> [Solves Problems] Copy Updates

docs/01-talk-objectives.md, docs/03-key-points.md, docs/04-ci-solves-problems.md, docs/05-supporting-quotes.md, docs/06-doc-tooling.md, docs/07-unit-testing.md, docs/08-Integration-testing.md, docs/10-running-tests-and-checks.md, docs/11-implementing-ci.md, docs/12-dependency-updates.md, docs/13-publishing-repositories.md
fix some spelling and grammar things i saw
any file that has differences
tough question. grammarly?
can haz good lang
n/a
=> fix: various spelling/grammar updates

.spelling, README.md
- Adds Pete and David to the **README**.
----
=> [update] adds David, Pete to README

docs/07-unit-testing.md
- Copy updates to the Unit Testing readme
=> [Unit Testing] Copy Updates

docs/12-dependency-updates.md
- Copy updates to the Implementing CI readme
=> [Dependency Updates] Copy Updates

docs/13-publishing-repositories.md
- Copy updates to the Publishing Repositories readme
=> [Publishing Repositories] Copy Updates

docs/16-talk-summation.md
- Copy updates to the Talk Summation readme
=> [Talk Summation] Copy Updates

docs/15-optimizations.md
- Copy updates to the Optimizations readme
=> [Optimizations] Copy Updates

docs/10-running-tests-and-checks.md
- Copy updates to the Running Tests and Checks readme
=> [Running Tests and Checks] Copy Updates

docs/01-talk-objectives.md, docs/02-what-is-ci.md, docs/03-key-points.md, docs/04-ci-solves-problems.md, docs/05-supporting-quotes.md, docs/06-doc-tooling.md, docs/07-unit-testing.md, docs/08-Integration-testing.md, docs/09-safety-checks.md, docs/10-running-tests-and-checks.md, docs/11-implementing-ci.md, docs/12-dependency-updates.md, docs/13-publishing-repositories.md, docs/14-ci-benefits.md, docs/15-optimizations.md, docs/16-talk-summation.md, docs/README.md
=> [update] adds header images to all docs

.spelling, docs/04-ci-solves-problems.md, yarn.lock
- Adds illustrations for CI
----
=> Add illustrations

.spelling, docs/02-what-is-ci.md
- Cites Wikipedia correctly
----
=> [bug] cites Wikipedia correctly in what-is-ci doc

docs/01-talk-objectives.md
- Fixes # [  n / a  ]
- Change: CodePen link
----
=> [update] replaces link to CodePen

docs/01-talk-objectives.md
- Fixes # [  n / a  ]
- Change: CodePen link
----
=> [update] replaces CodePen link

README.md
This improves a few wordings.
----
=> [update] Improve some wordings

README.md, docs/01-talk-objectives.md, docs/02-what-is-ci.md, docs/03-key-points.md, docs/04-ci-solves-problems.md, docs/05-supporting-quotes.md, docs/06-doc-tooling.md, docs/07-unit-testing.md, docs/08-integration-testing.md, docs/09-safety-checks.md, docs/10-running-tests-and-checks.md, docs/11-implementing-ci.md, docs/12-dependency-updates.md, docs/13-publishing-repositories.md, docs/14-ci-benefits.md, docs/15-optimizations.md, docs/16-talk-summation.md, docs/README.md
- Fixes #39
- Embeds fonts and adds query param to ensure they're referenced.
----
=> Update header images

.spelling, docs/09-safety-checks.md, yarn.lock
- Fixes N/A
- Adds commitlint to methods of keeping things clean
----
=> add commitlint on L18

README.md
=> [update] adds CircleCi badge

README.md
=> [update] adds links to the demo

README.md
- Provides contributing guidelines and information
- closes #28
----
=> [update] provides contributing info to the README

README.md, package.json, yarn.lock
- Adds demo deps
- [developer-ci-benefits-demo](https://github.com/yowainwright/developer-ci-benefits-demo)
- [developer-ci-benefits-demo-dependent](https://github.com/yowainwright/developer-ci-benefits-demo-dependent)
----
=> [version] adds demo, demo-dependent pckgs
